ALTER TABLE `posts` CHANGE COLUMN `ip` `ip` VARCHAR(88) NOT NULL;
ALTER TABLE `reports` CHANGE COLUMN `ip` `ip` VARCHAR(88) NOT NULL;
ALTER TABLE `banlist` CHANGE COLUMN `ip` `ip` VARCHAR(88) NOT NULL;
ALTER TABLE `loginattempts` CHANGE COLUMN `ip` `ip` VARCHAR(45) NOT NULL;